In [1]:
import numpy as np

# Load sudokus
sudoku = np.load("data/very_easy_puzzle.npy")
print("very_easy_puzzle.npy has been loaded into the variable sudoku")
print(f"sudoku.shape: {sudoku.shape}, sudoku[0].shape: {sudoku[0].shape}, sudoku.dtype: {sudoku.dtype}")

# Load solutions for demonstration
solutions = np.load("data/very_easy_solution.npy")
print()

# Print the first 9x9 sudoku...
print("First sudoku:")
print(sudoku[1], "\n")

# ...and its solution
print("Solution of first sudoku:")
solutions[1]

type(sudoku[1])
sudoku[1]

very_easy_puzzle.npy has been loaded into the variable sudoku
sudoku.shape: (15, 9, 9), sudoku[0].shape: (9, 9), sudoku.dtype: int8

First sudoku:
[[0 9 3 1 5 2 6 0 8]
 [8 6 2 7 0 3 1 9 5]
 [1 5 7 9 8 6 3 2 4]
 [9 7 8 4 2 1 0 3 6]
 [5 0 6 8 3 9 4 1 7]
 [3 4 1 5 6 7 2 8 9]
 [6 1 4 2 7 8 9 5 3]
 [7 3 9 6 1 5 8 4 2]
 [2 8 5 3 9 4 7 6 1]] 

Solution of first sudoku:


array([[0, 9, 3, 1, 5, 2, 6, 0, 8],
       [8, 6, 2, 7, 0, 3, 1, 9, 5],
       [1, 5, 7, 9, 8, 6, 3, 2, 4],
       [9, 7, 8, 4, 2, 1, 0, 3, 6],
       [5, 0, 6, 8, 3, 9, 4, 1, 7],
       [3, 4, 1, 5, 6, 7, 2, 8, 9],
       [6, 1, 4, 2, 7, 8, 9, 5, 3],
       [7, 3, 9, 6, 1, 5, 8, 4, 2],
       [2, 8, 5, 3, 9, 4, 7, 6, 1]], dtype=int8)

In [2]:
sudoku_1 = sudoku[1] 
sudoku_1

#access sudoku_1: is just like accessing a 2_d list 
sudoku_1
sudoku_1





array([[0, 9, 3, 1, 5, 2, 6, 0, 8],
       [8, 6, 2, 7, 0, 3, 1, 9, 5],
       [1, 5, 7, 9, 8, 6, 3, 2, 4],
       [9, 7, 8, 4, 2, 1, 0, 3, 6],
       [5, 0, 6, 8, 3, 9, 4, 1, 7],
       [3, 4, 1, 5, 6, 7, 2, 8, 9],
       [6, 1, 4, 2, 7, 8, 9, 5, 3],
       [7, 3, 9, 6, 1, 5, 8, 4, 2],
       [2, 8, 5, 3, 9, 4, 7, 6, 1]], dtype=int8)

In [3]:
import copy

In [4]:
class Sudoku_Partial_State:
    
    def __init__ (self, sudoku): 
        self.sudoku = sudoku
        self.possible_values = list(range(0,10))
        self.empty_location_list = []


    def is_above_zero(self):
        """This partial state is a goal state if every column/ row has a final value"""
        return np.all(self.sudoku > 0) #and sum no repetitions in column,rows, and 3x3 np.arrays
            
   
    def is_row_final_state(self):
        #checking for duplicates in rows
        row_number = 1
        for row in self.sudoku:
            unique_row = np.unique(row)
            if unique_row.size != len(row):
                print('There are duplicates in row:', row_number)
                return False
            else: row_number+=1
        return True
            
              
    def is_column_final_state(self):
        #checking for duplicates in columns
        column_number = 1
        for column in self.sudoku.T:
            unique_column = np.unique(column)
            if unique_column.size != len(column):
                print('There are duplicates in column:', column_number)
                return False
            else: column_number+=1
        return True
    
    def is_box_final_state(self):
        #checking for duplicates in each box
        #could be improved by running some for loop on it
        box_1 = self.sudoku[0:3,0:3]
        box_2 = self.sudoku[0:3,3:6]
        box_3 = self.sudoku[0:3,6:9]
        box_4 = self.sudoku[3:6,0:3]
        box_5 = self.sudoku[3:6,3:6]
        box_6 = self.sudoku[3:6,6:9]
        box_7 = self.sudoku[6:9,0:3]
        box_8 = self.sudoku[6:9,3:6]
        box_9 = self.sudoku[6:9,6:9]
        boxes_9 = [box_1,box_2,box_3,box_4,box_5,box_6,box_7,box_8,box_9]
        box_number = 1
        for box in boxes_9:
            #check if each box is unique
            unique_box = np.unique(box)
            if unique_box.size != 9:
                print('There are duplicates in box', box_number)
                return False
            else: box_number+=1  
        return True
    
    def is_goal(self):
        if self.is_row_final_state() and self.is_column_final_state() and self.is_box_final_state() and self.is_above_zero():
            True

    def get_empty_locations(self):
        #looks for the location of zeros.
        empty_location_arrays=np.where(self.sudoku==0)
        empty_location_list=list(zip(empty_location_arrays[0],empty_location_arrays[1])) 
        return empty_location_list
        
    def get_all_possible_values(self):
        return self.possible_values.copy()
    
    def get_possible_values(self,row,column):
        # create a deep copy: the method returns a new state, does not modify the existing one
        state = copy.deepcopy(self)
        possible_values = state.possible_values   
        
        #remove duplicates in rows
        row_array = self.sudoku[row]
        unique_row_list=list(np.unique(row_array))
        print('unique_row_list:', unique_row_list)
        print('possible_values_before',possible_values)
        for number in unique_row_list:   
            if number in possible_values:
                possible_values.remove(number)
            
            if len(possible_values) == 1:
                solution = possible_values[0]
                print('solution:',solution)
                return solution                
        print('possible_values_after_row',possible_values)
                        
        #remove duplicates in columns
        column_array = self.sudoku.T[column]
        unique_column_list = list(np.unique(column_array))
        print('unique_column_list:', unique_column_list)
        print('possible_values_before',possible_values)
        for number in unique_column_list:
            if number in possible_values:
                possible_values.remove(number)
                if len(possible_values) == 1:
                    solution = possible_values[0]
                    print('solution:',solution)
                    return solution
            
        print('possible_values_after_column',possible_values)

            
        #remove duplicates in boxes #check with Hasan how to make this optimal# I know that this is very bad lol

        #locate box:
        if row <4 and column <4:
            box = self.sudoku[0:3,0:3]
        if row <4 and column <4:
            box = self.sudoku[0:3,3:6]
        if row <4 and column <4:
            box = self.sudoku[0:3,6:9]
        if row <4 and column <4:
            box = self.sudoku[3:6,0:3]
        if row <4 and column <4:
            box = self.sudoku[3:6,3:6]
        if row <4 and column <4:
            box = self.sudoku[3:6,6:9]
        if row <4 and column <4:
            box = self.sudoku[6:9,0:3]
        if row <4 and column <4:
            box = self.sudoku[6:9,3:6]
        if row <4 and column <4:
            box = self.sudoku[6:9,6:9]
        
        box_list = sum(box.tolist(),[])
        print('box_list', box_list)
        print('possible_values_before',possible_values)
        for number in box_list:
            if number in possible_values:
                possible_values.remove(number)
                if len(possible_values) == 1:
                    solution = possible_values[0]
                    print('solution:',solution)
                    return solution    
        print('possible_values_after_box',possible_values)
        
        return possible_values
    
    
    def set_value(self, possible_value,row,column):
        new_state = self.sudoku
        new_state[row, column] = possible_value
        return new_state              
        

In [5]:
#print('sudoku_1: ', sudoku_1)
sudoku_one = Sudoku_Partial_State(sudoku_1)
sudoku_one.set_value(4,0,0)

len(sudoku_one.get_empty_locations())

4

In [6]:
True and True

True

In [7]:


def search_for_solution(sudoku):
    
    partial_sudoku_state = Sudoku_Partial_State(sudoku)
    
    #checking if sudoku is solved 
    if partial_sudoku_state.is_goal():
        print("Found a solution! Yay")
        return self.sudoku
    
    else: 
    #take the first empty location
        i = 0
        for empty_loc in range(0,len(partial_sudoku_state.get_empty_locations())):
            partial_sudoku_state.get_empty_locations[i] #for example we got the first location (0,0)

            #get possible values for this location
            possible_valid_values = partial_sudoku_state.get_possible_values(empty_loc[0],empty_loc[1]) # this has returned a list of possible number for ex. [3,4,5]

            #we will try each possible value in the possible_valid_values in a for loop: 
            for possible_value in possible_valid_values:
                new_sudoku_state = partial_sudoku_state.set_value(possible_value,empty_loc[0],empty_loc[1])
                i += 1

                search_for_solution(new_sudoku_state)

In [8]:
search_for_solution(sudoku_1)

TypeError: 'method' object is not subscriptable

In [9]:
s_2 =Sudoku_Solution(sudoku_2)

x=np.array(s_2.sudoku)
s_2[0,0] = 1
    
    

NameError: name 'Sudoku_Solution' is not defined

In [10]:
test_array = np.array([[1,2],[3,4]])
print(type(test_array))

test_array[0,0] = 5

test_array

<class 'numpy.ndarray'>


array([[5, 2],
       [3, 4]])